package com.qjq.crawler.dao.mysql;

import com.qjq.crawler.domain.CrawlerJobUser;
import com.qjq.crawler.domain.CrawlerJobUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlerJobUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int countByExample(CrawlerJobUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int deleteByExample(CrawlerJobUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int deleteByPrimaryKey(String jobid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int insert(CrawlerJobUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int insertSelective(CrawlerJobUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    List<CrawlerJobUser> selectByExample(CrawlerJobUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    CrawlerJobUser selectByPrimaryKey(String jobid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrawlerJobUser record, @Param("example") CrawlerJobUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByExample(@Param("record") CrawlerJobUser record, @Param("example") CrawlerJobUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByPrimaryKeySelective(CrawlerJobUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByPrimaryKey(CrawlerJobUser record);
}