package com.qjq.crawler.dao.mysql;

import com.qjq.crawler.domain.CrawlerUser;
import com.qjq.crawler.domain.CrawlerUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlerUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int countByExample(CrawlerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int deleteByExample(CrawlerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int insert(CrawlerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int insertSelective(CrawlerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    List<CrawlerUser> selectByExampleWithBLOBs(CrawlerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    List<CrawlerUser> selectByExample(CrawlerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    CrawlerUser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrawlerUser record, @Param("example") CrawlerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") CrawlerUser record, @Param("example") CrawlerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByExample(@Param("record") CrawlerUser record, @Param("example") CrawlerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByPrimaryKeySelective(CrawlerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(CrawlerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_user
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByPrimaryKey(CrawlerUser record);
}