package com.qjq.crawler.dao.mysql;

import com.qjq.crawler.domain.CrawlerUrllist;
import com.qjq.crawler.domain.CrawlerUrllistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlerUrllistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int countByExample(CrawlerUrllistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int deleteByExample(CrawlerUrllistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int deleteByPrimaryKey(String urllistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int insert(CrawlerUrllist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int insertSelective(CrawlerUrllist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    List<CrawlerUrllist> selectByExampleWithBLOBs(CrawlerUrllistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    List<CrawlerUrllist> selectByExample(CrawlerUrllistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    CrawlerUrllist selectByPrimaryKey(String urllistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrawlerUrllist record, @Param("example") CrawlerUrllistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") CrawlerUrllist record, @Param("example") CrawlerUrllistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByExample(@Param("record") CrawlerUrllist record, @Param("example") CrawlerUrllistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByPrimaryKeySelective(CrawlerUrllist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(CrawlerUrllist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    int updateByPrimaryKey(CrawlerUrllist record);
}