package com.qjq.crawler.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrawlerUrllistExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public CrawlerUrllistExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUrllistidIsNull() {
            addCriterion("urlListId is null");
            return (Criteria) this;
        }

        public Criteria andUrllistidIsNotNull() {
            addCriterion("urlListId is not null");
            return (Criteria) this;
        }

        public Criteria andUrllistidEqualTo(String value) {
            addCriterion("urlListId =", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidNotEqualTo(String value) {
            addCriterion("urlListId <>", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidGreaterThan(String value) {
            addCriterion("urlListId >", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidGreaterThanOrEqualTo(String value) {
            addCriterion("urlListId >=", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidLessThan(String value) {
            addCriterion("urlListId <", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidLessThanOrEqualTo(String value) {
            addCriterion("urlListId <=", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidLike(String value) {
            addCriterion("urlListId like", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidNotLike(String value) {
            addCriterion("urlListId not like", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidIn(List<String> values) {
            addCriterion("urlListId in", values, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidNotIn(List<String> values) {
            addCriterion("urlListId not in", values, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidBetween(String value1, String value2) {
            addCriterion("urlListId between", value1, value2, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidNotBetween(String value1, String value2) {
            addCriterion("urlListId not between", value1, value2, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistnameIsNull() {
            addCriterion("urlListName is null");
            return (Criteria) this;
        }

        public Criteria andUrllistnameIsNotNull() {
            addCriterion("urlListName is not null");
            return (Criteria) this;
        }

        public Criteria andUrllistnameEqualTo(String value) {
            addCriterion("urlListName =", value, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameNotEqualTo(String value) {
            addCriterion("urlListName <>", value, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameGreaterThan(String value) {
            addCriterion("urlListName >", value, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameGreaterThanOrEqualTo(String value) {
            addCriterion("urlListName >=", value, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameLessThan(String value) {
            addCriterion("urlListName <", value, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameLessThanOrEqualTo(String value) {
            addCriterion("urlListName <=", value, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameLike(String value) {
            addCriterion("urlListName like", value, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameNotLike(String value) {
            addCriterion("urlListName not like", value, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameIn(List<String> values) {
            addCriterion("urlListName in", values, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameNotIn(List<String> values) {
            addCriterion("urlListName not in", values, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameBetween(String value1, String value2) {
            addCriterion("urlListName between", value1, value2, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUrllistnameNotBetween(String value1, String value2) {
            addCriterion("urlListName not between", value1, value2, "urllistname");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userId like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userId not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNull() {
            addCriterion("isValid is null");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNotNull() {
            addCriterion("isValid is not null");
            return (Criteria) this;
        }

        public Criteria andIsvalidEqualTo(Integer value) {
            addCriterion("isValid =", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotEqualTo(Integer value) {
            addCriterion("isValid <>", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThan(Integer value) {
            addCriterion("isValid >", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThanOrEqualTo(Integer value) {
            addCriterion("isValid >=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThan(Integer value) {
            addCriterion("isValid <", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThanOrEqualTo(Integer value) {
            addCriterion("isValid <=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidIn(List<Integer> values) {
            addCriterion("isValid in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotIn(List<Integer> values) {
            addCriterion("isValid not in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidBetween(Integer value1, Integer value2) {
            addCriterion("isValid between", value1, value2, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotBetween(Integer value1, Integer value2) {
            addCriterion("isValid not between", value1, value2, "isvalid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crawler_urllist
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 18 11:17:50 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crawler_urllist
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}