package com.qjq.crawler.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrawlerJobExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public CrawlerJobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobidIsNull() {
            addCriterion("jobId is null");
            return (Criteria) this;
        }

        public Criteria andJobidIsNotNull() {
            addCriterion("jobId is not null");
            return (Criteria) this;
        }

        public Criteria andJobidEqualTo(String value) {
            addCriterion("jobId =", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotEqualTo(String value) {
            addCriterion("jobId <>", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidGreaterThan(String value) {
            addCriterion("jobId >", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidGreaterThanOrEqualTo(String value) {
            addCriterion("jobId >=", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidLessThan(String value) {
            addCriterion("jobId <", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidLessThanOrEqualTo(String value) {
            addCriterion("jobId <=", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidLike(String value) {
            addCriterion("jobId like", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotLike(String value) {
            addCriterion("jobId not like", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidIn(List<String> values) {
            addCriterion("jobId in", values, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotIn(List<String> values) {
            addCriterion("jobId not in", values, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidBetween(String value1, String value2) {
            addCriterion("jobId between", value1, value2, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotBetween(String value1, String value2) {
            addCriterion("jobId not between", value1, value2, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobnameIsNull() {
            addCriterion("jobName is null");
            return (Criteria) this;
        }

        public Criteria andJobnameIsNotNull() {
            addCriterion("jobName is not null");
            return (Criteria) this;
        }

        public Criteria andJobnameEqualTo(String value) {
            addCriterion("jobName =", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotEqualTo(String value) {
            addCriterion("jobName <>", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameGreaterThan(String value) {
            addCriterion("jobName >", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameGreaterThanOrEqualTo(String value) {
            addCriterion("jobName >=", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLessThan(String value) {
            addCriterion("jobName <", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLessThanOrEqualTo(String value) {
            addCriterion("jobName <=", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLike(String value) {
            addCriterion("jobName like", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotLike(String value) {
            addCriterion("jobName not like", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameIn(List<String> values) {
            addCriterion("jobName in", values, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotIn(List<String> values) {
            addCriterion("jobName not in", values, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameBetween(String value1, String value2) {
            addCriterion("jobName between", value1, value2, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotBetween(String value1, String value2) {
            addCriterion("jobName not between", value1, value2, "jobname");
            return (Criteria) this;
        }

        public Criteria andUrllistidIsNull() {
            addCriterion("urlListId is null");
            return (Criteria) this;
        }

        public Criteria andUrllistidIsNotNull() {
            addCriterion("urlListId is not null");
            return (Criteria) this;
        }

        public Criteria andUrllistidEqualTo(String value) {
            addCriterion("urlListId =", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidNotEqualTo(String value) {
            addCriterion("urlListId <>", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidGreaterThan(String value) {
            addCriterion("urlListId >", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidGreaterThanOrEqualTo(String value) {
            addCriterion("urlListId >=", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidLessThan(String value) {
            addCriterion("urlListId <", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidLessThanOrEqualTo(String value) {
            addCriterion("urlListId <=", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidLike(String value) {
            addCriterion("urlListId like", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidNotLike(String value) {
            addCriterion("urlListId not like", value, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidIn(List<String> values) {
            addCriterion("urlListId in", values, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidNotIn(List<String> values) {
            addCriterion("urlListId not in", values, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidBetween(String value1, String value2) {
            addCriterion("urlListId between", value1, value2, "urllistid");
            return (Criteria) this;
        }

        public Criteria andUrllistidNotBetween(String value1, String value2) {
            addCriterion("urlListId not between", value1, value2, "urllistid");
            return (Criteria) this;
        }

        public Criteria andMaxdepthIsNull() {
            addCriterion("maxDepth is null");
            return (Criteria) this;
        }

        public Criteria andMaxdepthIsNotNull() {
            addCriterion("maxDepth is not null");
            return (Criteria) this;
        }

        public Criteria andMaxdepthEqualTo(Integer value) {
            addCriterion("maxDepth =", value, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andMaxdepthNotEqualTo(Integer value) {
            addCriterion("maxDepth <>", value, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andMaxdepthGreaterThan(Integer value) {
            addCriterion("maxDepth >", value, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andMaxdepthGreaterThanOrEqualTo(Integer value) {
            addCriterion("maxDepth >=", value, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andMaxdepthLessThan(Integer value) {
            addCriterion("maxDepth <", value, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andMaxdepthLessThanOrEqualTo(Integer value) {
            addCriterion("maxDepth <=", value, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andMaxdepthIn(List<Integer> values) {
            addCriterion("maxDepth in", values, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andMaxdepthNotIn(List<Integer> values) {
            addCriterion("maxDepth not in", values, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andMaxdepthBetween(Integer value1, Integer value2) {
            addCriterion("maxDepth between", value1, value2, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andMaxdepthNotBetween(Integer value1, Integer value2) {
            addCriterion("maxDepth not between", value1, value2, "maxdepth");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeIsNull() {
            addCriterion("jobMaxSize is null");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeIsNotNull() {
            addCriterion("jobMaxSize is not null");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeEqualTo(Integer value) {
            addCriterion("jobMaxSize =", value, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeNotEqualTo(Integer value) {
            addCriterion("jobMaxSize <>", value, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeGreaterThan(Integer value) {
            addCriterion("jobMaxSize >", value, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("jobMaxSize >=", value, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeLessThan(Integer value) {
            addCriterion("jobMaxSize <", value, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeLessThanOrEqualTo(Integer value) {
            addCriterion("jobMaxSize <=", value, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeIn(List<Integer> values) {
            addCriterion("jobMaxSize in", values, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeNotIn(List<Integer> values) {
            addCriterion("jobMaxSize not in", values, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeBetween(Integer value1, Integer value2) {
            addCriterion("jobMaxSize between", value1, value2, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxsizeNotBetween(Integer value1, Integer value2) {
            addCriterion("jobMaxSize not between", value1, value2, "jobmaxsize");
            return (Criteria) this;
        }

        public Criteria andCrawlednumIsNull() {
            addCriterion("crawledNum is null");
            return (Criteria) this;
        }

        public Criteria andCrawlednumIsNotNull() {
            addCriterion("crawledNum is not null");
            return (Criteria) this;
        }

        public Criteria andCrawlednumEqualTo(Integer value) {
            addCriterion("crawledNum =", value, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andCrawlednumNotEqualTo(Integer value) {
            addCriterion("crawledNum <>", value, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andCrawlednumGreaterThan(Integer value) {
            addCriterion("crawledNum >", value, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andCrawlednumGreaterThanOrEqualTo(Integer value) {
            addCriterion("crawledNum >=", value, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andCrawlednumLessThan(Integer value) {
            addCriterion("crawledNum <", value, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andCrawlednumLessThanOrEqualTo(Integer value) {
            addCriterion("crawledNum <=", value, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andCrawlednumIn(List<Integer> values) {
            addCriterion("crawledNum in", values, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andCrawlednumNotIn(List<Integer> values) {
            addCriterion("crawledNum not in", values, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andCrawlednumBetween(Integer value1, Integer value2) {
            addCriterion("crawledNum between", value1, value2, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andCrawlednumNotBetween(Integer value1, Integer value2) {
            addCriterion("crawledNum not between", value1, value2, "crawlednum");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("startTime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("startTime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            addCriterion("startTime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            addCriterion("startTime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            addCriterion("startTime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("startTime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            addCriterion("startTime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("startTime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("startTime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("startTime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("startTime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("startTime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endTime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endTime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endTime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endTime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endTime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endTime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endTime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endTime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endTime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endTime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endTime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andJobstatusIsNull() {
            addCriterion("jobStatus is null");
            return (Criteria) this;
        }

        public Criteria andJobstatusIsNotNull() {
            addCriterion("jobStatus is not null");
            return (Criteria) this;
        }

        public Criteria andJobstatusEqualTo(String value) {
            addCriterion("jobStatus =", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotEqualTo(String value) {
            addCriterion("jobStatus <>", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusGreaterThan(String value) {
            addCriterion("jobStatus >", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusGreaterThanOrEqualTo(String value) {
            addCriterion("jobStatus >=", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusLessThan(String value) {
            addCriterion("jobStatus <", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusLessThanOrEqualTo(String value) {
            addCriterion("jobStatus <=", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusLike(String value) {
            addCriterion("jobStatus like", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotLike(String value) {
            addCriterion("jobStatus not like", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusIn(List<String> values) {
            addCriterion("jobStatus in", values, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotIn(List<String> values) {
            addCriterion("jobStatus not in", values, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusBetween(String value1, String value2) {
            addCriterion("jobStatus between", value1, value2, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotBetween(String value1, String value2) {
            addCriterion("jobStatus not between", value1, value2, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeIsNull() {
            addCriterion("jobMaxDomainSize is null");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeIsNotNull() {
            addCriterion("jobMaxDomainSize is not null");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeEqualTo(Integer value) {
            addCriterion("jobMaxDomainSize =", value, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeNotEqualTo(Integer value) {
            addCriterion("jobMaxDomainSize <>", value, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeGreaterThan(Integer value) {
            addCriterion("jobMaxDomainSize >", value, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("jobMaxDomainSize >=", value, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeLessThan(Integer value) {
            addCriterion("jobMaxDomainSize <", value, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeLessThanOrEqualTo(Integer value) {
            addCriterion("jobMaxDomainSize <=", value, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeIn(List<Integer> values) {
            addCriterion("jobMaxDomainSize in", values, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeNotIn(List<Integer> values) {
            addCriterion("jobMaxDomainSize not in", values, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeBetween(Integer value1, Integer value2) {
            addCriterion("jobMaxDomainSize between", value1, value2, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andJobmaxdomainsizeNotBetween(Integer value1, Integer value2) {
            addCriterion("jobMaxDomainSize not between", value1, value2, "jobmaxdomainsize");
            return (Criteria) this;
        }

        public Criteria andCurdepthIsNull() {
            addCriterion("curDepth is null");
            return (Criteria) this;
        }

        public Criteria andCurdepthIsNotNull() {
            addCriterion("curDepth is not null");
            return (Criteria) this;
        }

        public Criteria andCurdepthEqualTo(Integer value) {
            addCriterion("curDepth =", value, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCurdepthNotEqualTo(Integer value) {
            addCriterion("curDepth <>", value, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCurdepthGreaterThan(Integer value) {
            addCriterion("curDepth >", value, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCurdepthGreaterThanOrEqualTo(Integer value) {
            addCriterion("curDepth >=", value, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCurdepthLessThan(Integer value) {
            addCriterion("curDepth <", value, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCurdepthLessThanOrEqualTo(Integer value) {
            addCriterion("curDepth <=", value, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCurdepthIn(List<Integer> values) {
            addCriterion("curDepth in", values, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCurdepthNotIn(List<Integer> values) {
            addCriterion("curDepth not in", values, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCurdepthBetween(Integer value1, Integer value2) {
            addCriterion("curDepth between", value1, value2, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCurdepthNotBetween(Integer value1, Integer value2) {
            addCriterion("curDepth not between", value1, value2, "curdepth");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNull() {
            addCriterion("isValid is null");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNotNull() {
            addCriterion("isValid is not null");
            return (Criteria) this;
        }

        public Criteria andIsvalidEqualTo(Integer value) {
            addCriterion("isValid =", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotEqualTo(Integer value) {
            addCriterion("isValid <>", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThan(Integer value) {
            addCriterion("isValid >", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThanOrEqualTo(Integer value) {
            addCriterion("isValid >=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThan(Integer value) {
            addCriterion("isValid <", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThanOrEqualTo(Integer value) {
            addCriterion("isValid <=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidIn(List<Integer> values) {
            addCriterion("isValid in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotIn(List<Integer> values) {
            addCriterion("isValid not in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidBetween(Integer value1, Integer value2) {
            addCriterion("isValid between", value1, value2, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotBetween(Integer value1, Integer value2) {
            addCriterion("isValid not between", value1, value2, "isvalid");
            return (Criteria) this;
        }

        public Criteria andJobtypeIsNull() {
            addCriterion("jobType is null");
            return (Criteria) this;
        }

        public Criteria andJobtypeIsNotNull() {
            addCriterion("jobType is not null");
            return (Criteria) this;
        }

        public Criteria andJobtypeEqualTo(String value) {
            addCriterion("jobType =", value, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeNotEqualTo(String value) {
            addCriterion("jobType <>", value, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeGreaterThan(String value) {
            addCriterion("jobType >", value, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeGreaterThanOrEqualTo(String value) {
            addCriterion("jobType >=", value, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeLessThan(String value) {
            addCriterion("jobType <", value, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeLessThanOrEqualTo(String value) {
            addCriterion("jobType <=", value, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeLike(String value) {
            addCriterion("jobType like", value, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeNotLike(String value) {
            addCriterion("jobType not like", value, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeIn(List<String> values) {
            addCriterion("jobType in", values, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeNotIn(List<String> values) {
            addCriterion("jobType not in", values, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeBetween(String value1, String value2) {
            addCriterion("jobType between", value1, value2, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobtypeNotBetween(String value1, String value2) {
            addCriterion("jobType not between", value1, value2, "jobtype");
            return (Criteria) this;
        }

        public Criteria andJobconfigIsNull() {
            addCriterion("jobConfig is null");
            return (Criteria) this;
        }

        public Criteria andJobconfigIsNotNull() {
            addCriterion("jobConfig is not null");
            return (Criteria) this;
        }

        public Criteria andJobconfigEqualTo(String value) {
            addCriterion("jobConfig =", value, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigNotEqualTo(String value) {
            addCriterion("jobConfig <>", value, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigGreaterThan(String value) {
            addCriterion("jobConfig >", value, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigGreaterThanOrEqualTo(String value) {
            addCriterion("jobConfig >=", value, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigLessThan(String value) {
            addCriterion("jobConfig <", value, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigLessThanOrEqualTo(String value) {
            addCriterion("jobConfig <=", value, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigLike(String value) {
            addCriterion("jobConfig like", value, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigNotLike(String value) {
            addCriterion("jobConfig not like", value, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigIn(List<String> values) {
            addCriterion("jobConfig in", values, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigNotIn(List<String> values) {
            addCriterion("jobConfig not in", values, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigBetween(String value1, String value2) {
            addCriterion("jobConfig between", value1, value2, "jobconfig");
            return (Criteria) this;
        }

        public Criteria andJobconfigNotBetween(String value1, String value2) {
            addCriterion("jobConfig not between", value1, value2, "jobconfig");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table crawler_job
     * @mbggenerated  Mon Jul 18 11:40:27 CST 2016
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crawler_job
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 18 11:17:50 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}