package com.qjq.crawler.domain;

import java.util.Date;

public class CrawlerUrllist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_urllist.urlListId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String urllistid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_urllist.urlListName
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String urllistname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_urllist.userId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_urllist.ctime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_urllist.mtime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_urllist.isValid
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Integer isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_urllist.urls
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String urls;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_urllist.urlListId
     *
     * @return the value of crawler_urllist.urlListId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getUrllistid() {
        return urllistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_urllist.urlListId
     *
     * @param urllistid the value for crawler_urllist.urlListId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setUrllistid(String urllistid) {
        this.urllistid = urllistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_urllist.urlListName
     *
     * @return the value of crawler_urllist.urlListName
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getUrllistname() {
        return urllistname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_urllist.urlListName
     *
     * @param urllistname the value for crawler_urllist.urlListName
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setUrllistname(String urllistname) {
        this.urllistname = urllistname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_urllist.userId
     *
     * @return the value of crawler_urllist.userId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_urllist.userId
     *
     * @param userid the value for crawler_urllist.userId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_urllist.ctime
     *
     * @return the value of crawler_urllist.ctime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_urllist.ctime
     *
     * @param ctime the value for crawler_urllist.ctime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_urllist.mtime
     *
     * @return the value of crawler_urllist.mtime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_urllist.mtime
     *
     * @param mtime the value for crawler_urllist.mtime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_urllist.isValid
     *
     * @return the value of crawler_urllist.isValid
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_urllist.isValid
     *
     * @param isvalid the value for crawler_urllist.isValid
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_urllist.urls
     *
     * @return the value of crawler_urllist.urls
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getUrls() {
        return urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_urllist.urls
     *
     * @param urls the value for crawler_urllist.urls
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setUrls(String urls) {
        this.urls = urls;
    }
}