package com.qjq.crawler.domain;

import java.util.Date;

public class CrawlerUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.userId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.userName
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.levelId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String levelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.email
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.startDate
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.expireDate
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Date expiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.phone
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.ctime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.mtime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.isValid
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Integer isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_user.password
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.userId
     *
     * @return the value of crawler_user.userId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.userId
     *
     * @param userid the value for crawler_user.userId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.userName
     *
     * @return the value of crawler_user.userName
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.userName
     *
     * @param username the value for crawler_user.userName
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.levelId
     *
     * @return the value of crawler_user.levelId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getLevelid() {
        return levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.levelId
     *
     * @param levelid the value for crawler_user.levelId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setLevelid(String levelid) {
        this.levelid = levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.email
     *
     * @return the value of crawler_user.email
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.email
     *
     * @param email the value for crawler_user.email
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.startDate
     *
     * @return the value of crawler_user.startDate
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.startDate
     *
     * @param startdate the value for crawler_user.startDate
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.expireDate
     *
     * @return the value of crawler_user.expireDate
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Date getExpiredate() {
        return expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.expireDate
     *
     * @param expiredate the value for crawler_user.expireDate
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setExpiredate(Date expiredate) {
        this.expiredate = expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.phone
     *
     * @return the value of crawler_user.phone
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.phone
     *
     * @param phone the value for crawler_user.phone
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.ctime
     *
     * @return the value of crawler_user.ctime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.ctime
     *
     * @param ctime the value for crawler_user.ctime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.mtime
     *
     * @return the value of crawler_user.mtime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.mtime
     *
     * @param mtime the value for crawler_user.mtime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.isValid
     *
     * @return the value of crawler_user.isValid
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.isValid
     *
     * @param isvalid the value for crawler_user.isValid
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_user.password
     *
     * @return the value of crawler_user.password
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_user.password
     *
     * @param password the value for crawler_user.password
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }
}