package com.qjq.crawler.domain;

import java.util.Date;

public class CrawlerJobUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_job_user.jobId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String jobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_job_user.userId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_job_user.ctime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_job_user.mtime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_job_user.isValid
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    private Integer isvalid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_job_user.jobId
     *
     * @return the value of crawler_job_user.jobId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_job_user.jobId
     *
     * @param jobid the value for crawler_job_user.jobId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setJobid(String jobid) {
        this.jobid = jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_job_user.userId
     *
     * @return the value of crawler_job_user.userId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_job_user.userId
     *
     * @param userid the value for crawler_job_user.userId
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_job_user.ctime
     *
     * @return the value of crawler_job_user.ctime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_job_user.ctime
     *
     * @param ctime the value for crawler_job_user.ctime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_job_user.mtime
     *
     * @return the value of crawler_job_user.mtime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_job_user.mtime
     *
     * @param mtime the value for crawler_job_user.mtime
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_job_user.isValid
     *
     * @return the value of crawler_job_user.isValid
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_job_user.isValid
     *
     * @param isvalid the value for crawler_job_user.isValid
     *
     * @mbggenerated Mon Jul 18 11:17:50 CST 2016
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }
}