package com.qjq.crawler.dao.mysql;

import com.qjq.crawler.domain.CrawlerJob;
import com.qjq.crawler.domain.CrawlerJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlerJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    int countByExample(CrawlerJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    int deleteByExample(CrawlerJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    int deleteByPrimaryKey(String jobid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    int insert(CrawlerJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    int insertSelective(CrawlerJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    List<CrawlerJob> selectByExample(CrawlerJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    CrawlerJob selectByPrimaryKey(String jobid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrawlerJob record, @Param("example") CrawlerJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    int updateByExample(@Param("record") CrawlerJob record, @Param("example") CrawlerJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    int updateByPrimaryKeySelective(CrawlerJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_job
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    int updateByPrimaryKey(CrawlerJob record);
}