package com.qjq.economics.information.domain;

import java.util.Date;

public class ParseInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.id
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.title
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.author
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.time
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.sources
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private String sources;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.ctime
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.mtime
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.insert_type
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private Integer insertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.isvalid
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private Integer isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parse_information.content
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.id
     *
     * @return the value of parse_information.id
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.id
     *
     * @param id the value for parse_information.id
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.title
     *
     * @return the value of parse_information.title
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.title
     *
     * @param title the value for parse_information.title
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.author
     *
     * @return the value of parse_information.author
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.author
     *
     * @param author the value for parse_information.author
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.time
     *
     * @return the value of parse_information.time
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.time
     *
     * @param time the value for parse_information.time
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.sources
     *
     * @return the value of parse_information.sources
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public String getSources() {
        return sources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.sources
     *
     * @param sources the value for parse_information.sources
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setSources(String sources) {
        this.sources = sources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.ctime
     *
     * @return the value of parse_information.ctime
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.ctime
     *
     * @param ctime the value for parse_information.ctime
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.mtime
     *
     * @return the value of parse_information.mtime
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.mtime
     *
     * @param mtime the value for parse_information.mtime
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.insert_type
     *
     * @return the value of parse_information.insert_type
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public Integer getInsertType() {
        return insertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.insert_type
     *
     * @param insertType the value for parse_information.insert_type
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setInsertType(Integer insertType) {
        this.insertType = insertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.isvalid
     *
     * @return the value of parse_information.isvalid
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.isvalid
     *
     * @param isvalid the value for parse_information.isvalid
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parse_information.content
     *
     * @return the value of parse_information.content
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parse_information.content
     *
     * @param content the value for parse_information.content
     *
     * @mbggenerated Tue Aug 02 14:40:21 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }
}