package com.qjq.crawler.download.dao.mysql;

import com.qjq.crawler.download.domain.CrawlerTimerJob;
import com.qjq.crawler.download.domain.CrawlerTimerJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlerTimerJobMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    int countByExample(CrawlerTimerJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    int deleteByExample(CrawlerTimerJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    int insert(CrawlerTimerJob record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    int insertSelective(CrawlerTimerJob record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    List<CrawlerTimerJob> selectByExample(CrawlerTimerJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    CrawlerTimerJob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrawlerTimerJob record, @Param("example") CrawlerTimerJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    int updateByExample(@Param("record") CrawlerTimerJob record, @Param("example") CrawlerTimerJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    int updateByPrimaryKeySelective(CrawlerTimerJob record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table crawler_timer_job
     * @mbggenerated  Mon Aug 08 16:21:03 CST 2016
     */
    int updateByPrimaryKey(CrawlerTimerJob record);
}