package com.qjq.crawler.download.domain;

import java.util.Date;

public class CrawlerUrlJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_url_job.id
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_url_job.uid
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_url_job.jobId
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    private String jobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_url_job.ctime
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_url_job.mtime
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_url_job.isValid
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    private Integer isvalid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_url_job.id
     *
     * @return the value of crawler_url_job.id
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_url_job.id
     *
     * @param id the value for crawler_url_job.id
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_url_job.uid
     *
     * @return the value of crawler_url_job.uid
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_url_job.uid
     *
     * @param uid the value for crawler_url_job.uid
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_url_job.jobId
     *
     * @return the value of crawler_url_job.jobId
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public String getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_url_job.jobId
     *
     * @param jobid the value for crawler_url_job.jobId
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public void setJobid(String jobid) {
        this.jobid = jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_url_job.ctime
     *
     * @return the value of crawler_url_job.ctime
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_url_job.ctime
     *
     * @param ctime the value for crawler_url_job.ctime
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_url_job.mtime
     *
     * @return the value of crawler_url_job.mtime
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_url_job.mtime
     *
     * @param mtime the value for crawler_url_job.mtime
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_url_job.isValid
     *
     * @return the value of crawler_url_job.isValid
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_url_job.isValid
     *
     * @param isvalid the value for crawler_url_job.isValid
     *
     * @mbggenerated Fri Jul 22 17:15:26 CST 2016
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }
}