package com.qjq.crawler.download.domain;

import java.util.Date;

public class CrawlerTimerJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.id
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.delay
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private String delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.url
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.xpath
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private String xpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.noticeQueueName
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private String noticequeuename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.expendsType
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private Integer expendstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.jobId
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private String jobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.ctime
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.mtime
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.status
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_timer_job.desc
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.id
     *
     * @return the value of crawler_timer_job.id
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.id
     *
     * @param id the value for crawler_timer_job.id
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.delay
     *
     * @return the value of crawler_timer_job.delay
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public String getDelay() {
        return delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.delay
     *
     * @param delay the value for crawler_timer_job.delay
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setDelay(String delay) {
        this.delay = delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.url
     *
     * @return the value of crawler_timer_job.url
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.url
     *
     * @param url the value for crawler_timer_job.url
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.xpath
     *
     * @return the value of crawler_timer_job.xpath
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public String getXpath() {
        return xpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.xpath
     *
     * @param xpath the value for crawler_timer_job.xpath
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setXpath(String xpath) {
        this.xpath = xpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.noticeQueueName
     *
     * @return the value of crawler_timer_job.noticeQueueName
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public String getNoticequeuename() {
        return noticequeuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.noticeQueueName
     *
     * @param noticequeuename the value for crawler_timer_job.noticeQueueName
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setNoticequeuename(String noticequeuename) {
        this.noticequeuename = noticequeuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.expendsType
     *
     * @return the value of crawler_timer_job.expendsType
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public Integer getExpendstype() {
        return expendstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.expendsType
     *
     * @param expendstype the value for crawler_timer_job.expendsType
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setExpendstype(Integer expendstype) {
        this.expendstype = expendstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.jobId
     *
     * @return the value of crawler_timer_job.jobId
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public String getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.jobId
     *
     * @param jobid the value for crawler_timer_job.jobId
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setJobid(String jobid) {
        this.jobid = jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.ctime
     *
     * @return the value of crawler_timer_job.ctime
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.ctime
     *
     * @param ctime the value for crawler_timer_job.ctime
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.mtime
     *
     * @return the value of crawler_timer_job.mtime
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.mtime
     *
     * @param mtime the value for crawler_timer_job.mtime
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.status
     *
     * @return the value of crawler_timer_job.status
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.status
     *
     * @param status the value for crawler_timer_job.status
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_timer_job.desc
     *
     * @return the value of crawler_timer_job.desc
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_timer_job.desc
     *
     * @param desc the value for crawler_timer_job.desc
     *
     * @mbggenerated Mon Aug 08 15:28:59 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}